# Generated by Django 5.0 on 2024-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_shop_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="user_img"),
        ),
    ]
