# Generated by Django 5.0 on 2024-01-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
