# Generated by Django 5.0 on 2024-01-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_shop_base", "0001_initial"),
        ("events", "0002_event_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "to_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="e_shop_base.profile",
                    ),
                ),
            ],
        ),
    ]
