# Generated by Django 5.0 on 2024-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("suit", "Suit"),
                            ("blouse", "Blouse"),
                            ("t-shirt", "T-Shirt"),
                            ("skirt", "Skirt"),
                            ("pants", "Pants"),
                            ("skirt_suit", "Skirt Suit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("L", "Large"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                            ("quick", "My Choice is Quick"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fabric",
                    models.CharField(
                        choices=[
                            ("cotton", "Cotton"),
                            ("polyester", "Polyester"),
                            ("lycra", "Lycra"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
