# Generated by Django 5.0 on 2024-01-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_imgstocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
