# Generated by Django 5.0 on 2024-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_stock_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
