# Generated by Django 5.0 on 2024-01-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
