# Generated by Django 5.0 on 2024-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_purchase_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="size",
            field=models.CharField(
                choices=[
                    ("L", "Large"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("XL", "Extra Large"),
                    ("XXL+", "Double Extra Large+"),
                ],
                max_length=10,
            ),
        ),
    ]
