# Generated by Django 5.0 on 2024-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_alter_stock_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imgstocks",
            name="img",
            field=models.ImageField(upload_to="stock_img"),
        ),
    ]
